### PR TITLE
Feature/trezor-ui-components

### PR DESCRIPTION
**Pull request by slowbackspace**
- trezor ui components all the things

also closes https://github.com/trezor/trezor-wallet/issues/428
screenshot from dev build:
Screenshot 2019-03-22 at 12 25 39

### CODE REVIEW

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
I think there should be some space between tooltip and content 
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
Do we want an autocomplete?

image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
too big?

image

**Comment by slowbackspace** [comment]
> https://github.com/trezor/trezor-wallet/pull/460#issuecomment-476124659
fixed in https://github.com/trezor/trezor-wallet/pull/465

**Comment by vladimirvolek** [comment]
not centered

image

**Comment by vladimirvolek** [comment]
disabled textarea outline?

image

**Comment by vladimirvolek** [comment]
Menu footer is not the same as page footer.

image

**Comment by vladimirvolek** [comment]
cross also too big 
image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
Missing select icon

image

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
This icon is too big.

image

**Comment by vladimirvolek** [comment]
image

**Comment by slowbackspace** [comment]
> Do we want an autocomplete?
> 
> image

that seems to be a chrome issue unrelated to this PR.



> Missing select icon (this screen is from master)
> 
> image
> image

should be fixed in https://github.com/trezor/trezor-ui-components/pull/148

>image

fixed in https://github.com/trezor/trezor-ui-components/pull/144

**Comment by vladimirvolek** [comment]
image

**Comment by vladimirvolek** [comment]
paragraph padding
image

**Pull request merged**
